---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-file-integrity
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-file-integrity
  namespace: openshift-file-integrity
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: file-integrity-operator
  namespace: openshift-file-integrity
spec:
  name: file-integrity-operator
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace

