apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operators
  namespace: openshift-gitops
spec:
  destination:
    namespace: gitops-test
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: false
    path: ./tenant/operator
    repoURL: https://github.com/richmitch/gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true