apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: gitops-managed-namespaces
  namespace: governance-policies
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: gitops-tests-namespace
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: gitops-tests
                  labels:
                    argocd.argoproj.io/managed-by: openshift-gitops
          remediationAction: inform
          severity: high
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: gitops-managed-namespaces-placement
  namespace: governance-policies
placementRef:
  name: local-cluster
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: gitops-managed-namespaces
    apiGroup: policy.open-cluster-management.io
    kind: Policy
