apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: local-cluster
  namespace: governance-policies
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  clusterSelector:
    matchExpressions:
    - key: name
      operator: In
      values:
      - local-cluster